apiVersion: v1
baseDomain: @baseDomain@ 
compute: 
- name: worker
  replicas: 0 
controlPlane: 
  name: master
  replicas: 3 
metadata:
  name: @name@ 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OVNKubernetes 
  serviceNetwork: 
  - 172.30.0.0/16
  machineNetwork:
    - cidr: @cidr@.0/24
platform:
  none: {}
fips: false 
pullSecret: '...'
sshKey: '...'
